### ISSUE TITLE
Cubari gist issue, Author and Artist name not shown in UI

### ISSUE THREAD

**Issue by flamekiller22** [appu1232/guyamoe#111]
Cubari gist issue, Author and Artist name not shown in UI.

You can check this [link.](https://cubari.moe/read/gist/northern-blade/) and check the raw json data.
It's not just this case it's been like this for all of them.

![The UI of the above mentioned link.](https://user-images.githubusercontent.com/90386026/133438505-39465da8-3d19-4751-8c7f-2493fdcd161d.png)

**Comment by flamekiller22** [comment]
Hey @appu1232 any updates on this??

**Comment by Algoinde** [comment]
I could add this a bit later, the data should be already in the template I think.

**Comment by flamekiller22** [comment]
Thanks @Algoinde.

**Comment by appu1232** [comment]
I've added the change, will deploy it to prod soon.

**Comment by appu1232** [comment]
It should be working now: https://cubari.moe/read/gist/northern-blade/ Sorry for taking so long, let me know if there's any issues.
