### ISSUE TITLE
Getting 500 server error for my gdrive gist

### ISSUE THREAD

**Issue by custom-ship** [appu1232/guyamoe#113]
I have two gdrive gists. One that I created 5 months ago and one that I created just now. The previous one works very well but the recent one gives 500 error whatever I do. The unix timestamps are correct (I think) as mentioned in the closed issue. 
The previous one is -
https://guya.moe/proxy/gist/Jszg1/
Gist - https://raw.githubusercontent.com/rohiCoder/selfhosted-manga-cubari/main/AoT(complete)

The current one - https://guya.moe/proxy/gist/Jrzu5/
Gist - https://raw.githubusercontent.com/rohiCoder/selfhosted-manga-cubari/main/Kny(complete)

Please direct me as to what I am missing.

**Comment by Algoinde** [comment]
You have unescaped `"`s in the description. Use this tool to catch any mistakes like these: https://jsonformatter.curiousconcept.com/

**Comment by custom-ship** [comment]
> You have unescaped `"`s in the description. Use this tool to catch any mistakes like these: https://jsonformatter.curiousconcept.com/

Removed those " but still it shows error. To be sure I also put it in the website and copied over the fixed json.

**Comment by custom-ship** [comment]
> > You have unescaped `"`s in the description. Use this tool to catch any mistakes like these: https://jsonformatter.curiousconcept.com/
> 
> Removed those " but still it shows error. To be sure I also put it in the website and copied over the fixed json.

Sorry the problem now seemed to be my git.io link. Thanks for such quick help. I'll close the issue. Sorry 😔
