### ISSUE TITLE
Support imgbb host

### ISSUE THREAD

**Issue by Ever4engel** [appu1232/guyamoe#121]
Hey,
(addition to cubari.moe)
Is it possible to support this lossless image host as proxy please https://imgbb.com/ ?

here a sample link https://ibb.co/album/QXZ0mZ there is 20 images there.

anyway thanks a lot for your framework guys it serves a lot to many teams.

**Comment by funkyhippo** [comment]
Closing because we don't support proxy functionality on Guya; tracked by https://github.com/subject-f/cubarimoe/issues/13 instead.
