### ISSUE TITLE
Migrate Kaguya to another host

### ISSUE THREAD

**Issue by Ever4engel** [appu1232/guyamoe#122]
Cubari.moe support now [Imgbb](https://imgbb.com/) host, this image host support lossless image compression hosts (32mb per file)
you can set never expire to your images/albums. it is already known, i think everybody knows about that, but Imgur host compress all images that has a storage larger than 1mb.

anyway thanks for this website, it is brilliant.

**Comment by Algoinde** [comment]
Kaguya is not hosted on Imgur though.

**Comment by Ever4engel** [comment]
Bruh i checked Oshi no ko and assumed it's same for all the content in the website...

**Comment by Algoinde** [comment]
Oshi no Ko is also not Imgur.
