### ISSUE TITLE
Option to disable scrolling when clicking outside of manga.

### ISSUE THREAD

**Issue by kilpsz** [appu1232/guyamoe#69]
Would be nice to have an option to disable scrolling up/down at all when clicking anywhere on the screen and/or outside of the pictures.

https://i.imgur.com/hs4W6JK.jpeg So clicking on the highlighted areas would not scroll up/down.

I tried all the settings, hopefully i didnt miss it.

**Comment by Algoinde** [comment]
It's actually implemented in the newer scrolling rework branch, but it's not production-ready yet. I will backport it to the main branch today if I have time.

**Comment by Algoinde** [comment]
Closed by 202ec653be6371c11b36612c738012da073d9e15
