### ISSUE TITLE
The AGPL licence is the web app version of the GPL so maybe you want to check it out.

### ISSUE THREAD

**Issue by tuxayo** [appu1232/guyamoe#9]
First amazing app. You have motivated me to read the manga after finishing the anime. Thanks a lot <3

Second you've made it libre/open source, this is even better! :D

\<end-fanboying-fangirling/>

### The actual point

So the AGPL is the web app version of the GPL otherwise the copyleft won't be applied in practice.

https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License

I guess copyleft is your intent since you are using the GPL.

Since you seems to have only 3 copyright holders, changing to the AGPL is doable if you want you.

**Comment by appu1232** [comment]
Hey, glad you got into the manga because of us! Will look into this and change it later today when I can. Thanks for the info.
