### ISSUE TITLE
Cubari gist 500-ing server

### ISSUE THREAD

**Issue by xrabohrok** [appu1232/guyamoe#96]
I'm trying to create a sort of master reading list for a comic contest, so I generated a cubari.moe gist that would hopefully help me with that.  Unfortunately, I get a 500 response with it, like so:

https://cubari.moe/read/gist/JOiI4/ 

For convenience, the git.io shortened link refers to this revision of this gist: https://gist.github.com/xrabohrok/0b24ba6660c030fd9c446b9eb62d2214 

My only guess is that the server is not too happy with receiving about 153 chapters in a go, but the 500 error doesn't give me a lot to go on.  Love the site otherwise.

Thanks

**Comment by xrabohrok** [comment]
I noticed I was missing the overall `artist` field and updated the `last_updated` fields to be strings, no dice.

**Comment by funkyhippo** [comment]
I believe your timestamps are too long; it should be in seconds rather than milliseconds.

**Comment by xrabohrok** [comment]
Yep, that turned out to be the problem, we're in business now.
https://cubari.moe/read/gist/JOitN/
I'll leave the honor of closing the issue to you, I don't know if this is something you want to address further or not.
Thanks!

**Comment by funkyhippo** [comment]
Actually, I just pushed an upstream fix so your original link works now. I appreciate the report!

(Side note but it looks like your git.io links point to specific commits. If you want it to update then you should point it to the raw gist instead (eg. [this](https://gist.githubusercontent.com/xrabohrok/0b24ba6660c030fd9c446b9eb62d2214/raw/)))

**Comment by xrabohrok** [comment]
You know, that is way more convenient and keeps me from having to generate new shortened URL's every time, I appreciate the heads up.

I was doing it by special direction of [the guide](https://www.reddit.com/r/manga/comments/mcicbp/sl_how_to_host_a_series_on_imgur_with_guyamoe/) linked from the FAQ, just in case you wondered where that came from.
